### ISSUE TITLE
Similarity between v1.1.1 and v1.1.0 release files

### ISSUE THREAD

**Issue by caibinqing** [AlexxIT/openmiio_agent#2]
Hello, it appears that the release files for v1.1.1 are the same as those for v1.1.0. Could there be an error?

- md5: 26ae806b2011febc3dad35367fca17d3
https://github.com/AlexxIT/openmiio_agent/releases/download/v1.1.1/openmiio_agent_arm
https://github.com/AlexxIT/openmiio_agent/releases/download/v1.1.0/openmiio_agent_arm

- md5: 93459b58872eac448a2be81da863950c
https://github.com/AlexxIT/openmiio_agent/releases/download/v1.1.1/openmiio_agent_mips
https://github.com/AlexxIT/openmiio_agent/releases/download/v1.1.0/openmiio_agent_mips

**Comment by AlexxIT** [comment]
Thanks! You right. I have updated binaries.
Anyway. I have plan to release new version with some heartbeat mqtt messages.
And only after that release next Xiaomi integration.
