### ISSUE TITLE
Add support for zigbee over TTY (dongle mode) for E1

### ISSUE THREAD

**Issue by stolen** [AlexxIT/openmiio_agent#3]
`openmiio_agent` can act as a TCP server (`--zigbee.tcp` option) which allows to use a hub in ZHA or zigbee2mqtt.  
This, however, requires a reliable Wi-Fi network.  
E1 hub has `/dev/ttyGS0` device which is connected to CDC ACM exposed to the USB host.

For example, E1 is plugged to a generic linux box.
E1 side:
```
/ # cat /dev/ttyGS0 
hello from host
^C
/ # echo 'ack from E1' > /dev/ttyGS0
/ # 
```
Host side:
```
$ echo -ne 'hello from host\r\n' > /dev/ttyACM0
$ pyserial-miniterm /dev/ttyACM0
--- Miniterm on /dev/ttyACM0  9600,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ack from E1
```

New option (say, `zigbee.tty=/dev/ttyGS0`) may allow using E1 hub as a plain zigbee dongle.
This mode would eliminate Wi-Fi communication making the overall setup more reliable.

**Comment by AlexxIT** [comment]
This is an interesting research. But I don't think it makes much sense for openmiio.
Because the E1 can't do anything but Zigbee. And the above can be done with socat. Just need to find a version for ARM.

**Comment by stolen** [comment]
Thank you for response!  
You are right, socat would be an easier fit for this particular task.

P.S. This is an awesome project! Thank you for your work!
