### ISSUE TITLE
Can openmiio_agent be set to start automatically upon startup? 

### ISSUE THREAD

**Issue by ChunMengLu** [AlexxIT/openmiio_agent#4]
Mijia_Hub_V2 (lumi.gateway.mcn001) 1.0.6_0016

I have studied it, and there is a section of code at the end of the `/etc/init.d/rcS` file:

```bash
CUSTOM_POST_INIT=/data/scripts/post_init.sh
if [ -x ${CUSTOM_POST_INIT} ]; then
    ${CUSTOM_POST_INIT} &
else
    fw_manager.sh -r
fi
```

If we create a `/data/scripts/post_init.sh` file with the following code, it should enable auto-start after boot:

```bash
#!/bin/sh
fw_manager.sh -h
/data/openmiio_agent miio mqtt cache central z3 --zigbee.tcp=8888 > /var/log/openmiio.log 2>&1 &
```

I missed `fw_manager.sh -h` during my experiment, and now it won't start. Σ( ° △ °|||)︴

**Comment by AlexxIT** [comment]
As I can understand, you broke your gateway because broke startup process. This is the reason why I'm not play with startup scripts. Any little mistake can broke gateway. And you even can't reset a gateway.

**Comment by ChunMengLu** [comment]
Thanks，Due to the special network environment of the customer, ha cannot use github, and openmiio_agent is installed manually. I will buy another one and try again!

**Comment by AlexxIT** [comment]
It is possible to install openmiio from another link or local drive. I use this for development

https://github.com/AlexxIT/XiaomiGateway3/blob/52d14e8e3979a0f95e164cd7fecb260997d829ce/custom_components/xiaomi_gateway3/__init__.py#L94
